### ISSUE TITLE
NN_LARS

### ISSUE THREAD

**Issue by FKShi** [nonmin/EIS-DRT#1]
Hi Xin Li,

Thank you for your sharing of your wonderful work. I am interested in the DRT method and want to reconstruct your work. I got an issue that I could not find the function NN_LARS used in sms_DRT.m and no results helpful online. Could you please help me with that? 

Thank you in advance.

**Comment by nonmin** [comment]
Hey, thanks for your interests.  
The NN_LARS (and other necessary sub-functions) are contained in the sms_DRT.m
From line 86:
function [out] = NN_LARS(A, b, delta)
% Non-negative LARS algorithm
% based on code of Martin Slawski, paper DOI: 10.1214/13-EJS868

I am guessing you are seeking for the code of Martin Slawski?
It is the NNLSLab package in his website.
https://sites.google.com/site/slawskimartin/code

**Comment by FKShi** [comment]
Thanks very much,  you are exactly right,  I am curious about the code.
I am using python and not really familiar with Matlab, so I wanna find the corresponding function in Python.
________________________________
